// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq0UI72IJUQ9ho2KuCAg7WAd4AvXYILfw',
    appId: '1:607599265434:web:4b08ac6f2eb73ff1b98123',
    messagingSenderId: '607599265434',
    projectId: 'parkin-e5423',
    authDomain: 'parkin-e5423.firebaseapp.com',
    storageBucket: 'parkin-e5423.appspot.com',
    measurementId: 'G-512FPTNV41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9Er-YR4vFN9ixDz1k0bi40u52RBaQ7XA',
    appId: '1:607599265434:android:26b208c69e380764b98123',
    messagingSenderId: '607599265434',
    projectId: 'parkin-e5423',
    storageBucket: 'parkin-e5423.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDdNeaiwx-FuSqVpCsqTqkjglKN0YiWyE',
    appId: '1:607599265434:ios:3a7cf85b91a5bf79b98123',
    messagingSenderId: '607599265434',
    projectId: 'parkin-e5423',
    storageBucket: 'parkin-e5423.appspot.com',
    iosBundleId: 'com.example.parkin',
  );
}
